### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by mikeireland** [rconan/CEO#23]
It would be helpful for dependencies to be explicitly given in the README file. e.g. which version of CUDA has this been tested on? 

Being unfamiliar with noweb, "make doc" also isn't quite functioning... 

zlibraryshapes.geometric.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/shapes/pgflibraryshape
s.geometric.code.tex))
! I can't find file `tikzlibrarybending.code.tex'.

**Comment by rconan** [comment]
Hi Mike,

Yes I still have to right a proper INSTALL note.
CUDA7.0 is the version I am using now, CEO used to work with earlier 
version.

For the doc, you need at least texlive 2014.
I am familiar with the  error you got, it means you are using texlive 2013.

The python doc is online at http://rconan.github.io/CEO/

Cheers
Rod

On 03/07/2016 08:22 PM, mikeireland wrote:
>
> It would be helpful for dependencies to be explicitly given in the 
> README file. e.g. which version of CUDA has this been tested on?
>
> Being unfamiliar with noweb, "make doc" also isn't quite functioning...
>
> zlibraryshapes.geometric.code.tex
> (/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/shapes/pgflibraryshape
> s.geometric.code.tex))
> ! I can't find file `tikzlibrarybending.code.tex'.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rconan/CEO/issues/23>.
>


-- 
Rodolphe Conan
Adaptive Optics Scientist
GMTO Corporation
+1 (626) 204 0507
