### ISSUE TITLE
CEO crashes if a source object is defined twice

### ISSUE THREAD

**Issue by mvandam** [rconan/CEO#71]
import ceo

gmt = ceo.GMT_MX()
~gmt
ngs = ceo.Source("K",zenith=[0.],azimuth=[0.],magnitude=[10],rays_box_size=25.5,rays_box_sampling=481,rays_origin=[0,0,25])

~ngs
gmt.propagate(ngs)

ngs = ceo.Source("K",zenith=[0.],azimuth=[0.],magnitude=[10],rays_box_size=25.5,rays_box_sampling=481,rays_origin=[0,0,25])

This produces the following error (on three different machines):
(CEO)>ERROR: invalid argument in source.nw at line 766

**Comment by rconan** [comment]
The issue was related to the update of the truss, some unnecessary deallocation of arrays
